# Generated by Django 2.1.2 on 2020-12-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_sample_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_4',
            field=models.TextField(blank=True, null=True, verbose_name='使用重量(2.5kg単位,デッドリフト)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_5',
            field=models.TextField(blank=True, null=True, verbose_name='使用重量(2.5kg単位,ベンチプレス)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.TextField(blank=True, null=True, verbose_name='使用重量(2.5kg単位,スクワット)'),
        ),
    ]
