# Generated by Django 2.1.2 on 2020-12-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201230_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='使用重量(2.5kg単位,BIG3も書けば-)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='使用重量(2.5kg単位,スクワット)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='使用重量(2.5kg単位,デッドリフト)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='使用重量(2.5kg単位,ベンチプレス)'),
        ),
    ]
