# Generated by Django 2.1.2 on 2020-12-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201230_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='スクワット(kg)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='デッドリフト(kg)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ベンチプレス(kg))'),
        ),
    ]
